# Generated by Django 3.1.1 on 2020-09-17 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Women'), ('2', 'Men'), ('3', 'Kids'), ('4', 'Accessories'), ('5', 'Cosmetics')], default='1', max_length=20)),
                ('product_title', models.CharField(max_length=100)),
                ('uploaded_by', models.CharField(choices=[('1', 'admin')], default='1', max_length=20)),
                ('uploaded_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.productinfo')),
            ],
        ),
    ]
