# Generated by Django 3.1.1 on 2020-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='category',
            field=models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Kids', 'Kids'), ('Accessories', 'Accessories'), ('Cosmetics', 'Cosmetics')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='uploaded_by',
            field=models.CharField(choices=[('admin', 'admin')], default='1', max_length=20),
        ),
    ]
