# Generated by Django 3.1.1 on 2020-09-17 14:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_auto_20200917_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='price',
            field=models.IntegerField(default=0, help_text='Please specify price in $'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=8),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='uploaded_by',
            field=models.CharField(choices=[('admin', 'admin')], default='admin', max_length=20),
        ),
    ]
